# Generated by Django 4.1.3 on 2022-12-02 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfume', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='perfume',
        ),
    ]
