# Generated by Django 4.1.3 on 2022-12-06 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfume', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='grade',
            field=models.FloatField(blank=True, default=5),
        ),
    ]
