# Generated by Django 4.1.3 on 2022-12-08 05:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('perfume', '0002_remove_perfume_base_notes_remove_perfume_heart_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfume',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='like_perfume', to=settings.AUTH_USER_MODEL),
        ),
    ]
