# Generated by Django 4.1.3 on 2022-12-09 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfume', '0003_perfume_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='survey',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='review',
            name='bad_content',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='review',
            name='good_content',
            field=models.TextField(blank=True, default=''),
        ),
    ]
