# Generated by Django 4.1.3 on 2022-12-10 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfume', '0004_review_survey_alter_review_bad_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
