# Generated by Django 4.1.3 on 2022-12-10 14:29

from django.db import migrations, models
import perfume.models


class Migration(migrations.Migration):

    dependencies = [
        ('perfume', '0005_alter_review_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='image',
            field=models.ImageField(max_length=255, null=True, upload_to=perfume.models.rename_reviewimage),
        ),
    ]
