# Generated by Django 4.1.3 on 2022-12-04 09:06

import custom_perfume.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NoteCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PackageCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(max_length=255, upload_to=custom_perfume.models.upload_to_package_image)),
                ('package_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custom_perfume.packagecategory')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('kor_name', models.CharField(max_length=100)),
                ('image', models.ImageField(max_length=255, null=True, upload_to=custom_perfume.models.upload_to_note_image)),
                ('note_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custom_perfume.notecategory')),
            ],
        ),
        migrations.CreateModel(
            name='CustomPerfume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('logo', models.ImageField(max_length=255, upload_to=custom_perfume.models.upload_to_custom_perfume_logo)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('note01', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note01', to='custom_perfume.note')),
                ('note02', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note02', to='custom_perfume.note')),
                ('note03', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note03', to='custom_perfume.note')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custom_perfume.package')),
            ],
        ),
    ]
