# Generated by Django 4.1.3 on 2022-12-06 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom_perfume', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='note_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='note01', to='custom_perfume.notecategory'),
        ),
    ]
