# Generated by Django 4.1.3 on 2022-12-14 00:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('custom_perfume', '0002_alter_note_note_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customperfume',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_perfume', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customperfume',
            name='note01',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='note01', to='custom_perfume.note'),
        ),
        migrations.AlterField(
            model_name='customperfume',
            name='note02',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='note02', to='custom_perfume.note'),
        ),
        migrations.AlterField(
            model_name='customperfume',
            name='note03',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='note03', to='custom_perfume.note'),
        ),
        migrations.AlterField(
            model_name='customperfume',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package', to='custom_perfume.package'),
        ),
    ]
